# Generated by Django 4.1.1 on 2022-09-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeheadmodel',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='police_admin_profile'),
        ),
    ]
