# Generated by Django 4.1.1 on 2022-09-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
