# Generated by Django 4.1.1 on 2022-09-11 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggresssioncasemodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exploitationcasemodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='motorincidentcasemodel',
            name='category',
        ),
        migrations.AlterField(
            model_name='abusecasemodel',
            name='category',
            field=models.OneToOneField(default='f8fb2a71-c333-4cf5-9e20-413dcfe9fd90', on_delete=django.db.models.deletion.CASCADE, to='app.categorymodel'),
        ),
        migrations.AlterField(
            model_name='intoxicationcasemodel',
            name='category',
            field=models.OneToOneField(default='439b17ec-6cc4-4fb6-8814-c3b06d899deb', on_delete=django.db.models.deletion.CASCADE, to='app.categorymodel'),
        ),
        migrations.AlterField(
            model_name='otherscasemodel',
            name='category',
            field=models.OneToOneField(default='4b408337-35d4-480f-9a82-6cfe4011b36d', on_delete=django.db.models.deletion.CASCADE, to='app.categorymodel'),
        ),
    ]
