# Generated by Django 4.1.1 on 2022-09-10 07:32

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categorymodel_alter_generalcasemodel_latittude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalcasemodel',
            old_name='file',
            new_name='media',
        ),
        migrations.RemoveField(
            model_name='generalcasemodel',
            name='location',
        ),
        migrations.AddField(
            model_name='generalcasemodel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalcasemodel',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalcasemodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generalcasemodel',
            name='height',
            field=models.FloatField(blank=True, null=True, validators=[app.validators.validate_severity]),
        ),
        migrations.AddField(
            model_name='generalcasemodel',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='id_card'),
        ),
        migrations.AddField(
            model_name='generalcasemodel',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalcasemodel',
            name='severity',
            field=models.FloatField(default=0, validators=[app.validators.validate_severity]),
        ),
    ]
