# Generated by Django 4.1.1 on 2022-09-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_personmodel_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
