# Generated by Django 4.1.1 on 2022-09-11 07:58

import app.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_aggresssioncasemodel_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseImagesModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='case_img')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('severity', models.FloatField(default=0, validators=[app.validators.validate_severity])),
                ('description', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='case_media')),
                ('latittude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('who_is_abused', models.CharField(choices=[('MEN', 'MEN'), ('WOMEN', 'WOMEN'), ('CHILD', 'CHILD'), ('OTHER', 'OTHER')], max_length=50)),
                ('abuse_type', models.CharField(choices=[('PHYSICAL', 'PHYSICAL'), ('MENTAL', 'MENTAL')], max_length=50)),
                ('injurured', models.BooleanField(default=False)),
                ('injururies', models.TextField(blank=True, null=True)),
                ('drugs', models.BooleanField(default=False)),
                ('alcohol', models.BooleanField(default=False)),
                ('consumption_level', models.FloatField(blank=True, null=True, validators=[app.validators.validate_alcoholic])),
                ('intoxicant', models.TextField(blank=True, null=True)),
                ('troubling_others', models.BooleanField(default=False)),
                ('weapon_used', models.BooleanField(default=False)),
                ('weapons_used', models.TextField(blank=True, null=True)),
                ('others_property_damaged', models.BooleanField(default=False)),
                ('perposefuly_damaged', models.BooleanField(default=False)),
                ('victim', models.CharField(choices=[('MINOR', 'MINOR'), ('FEMALE', 'FEMALE'), ('CHILD', 'CHILD'), ('OTHER', 'OTHER')], max_length=50)),
                ('category', models.OneToOneField(default='4b408337-35d4-480f-9a82-6cfe4011b36d', on_delete=django.db.models.deletion.CASCADE, to='app.categorymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('id_card', models.ImageField(blank=True, null=True, upload_to='id_card')),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=50, null=True)),
                ('height', models.FloatField(blank=True, null=True, validators=[app.validators.validate_severity])),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_suspects', to='app.casemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='abusecasemodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='AggresssionCaseModel',
        ),
        migrations.DeleteModel(
            name='ExploitationCaseModel',
        ),
        migrations.RemoveField(
            model_name='intoxicationcasemodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='MotorIncidentCaseModel',
        ),
        migrations.RemoveField(
            model_name='otherscasemodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='AbuseCaseModel',
        ),
        migrations.DeleteModel(
            name='IntoxicationCaseModel',
        ),
        migrations.DeleteModel(
            name='OthersCaseModel',
        ),
        migrations.AddField(
            model_name='caseimagesmodel',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_case_imgs', to='app.casemodel'),
        ),
    ]
