# Generated by Django 4.1.1 on 2022-09-10 12:05

import app.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_file_generalcasemodel_media_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('id_card', models.ImageField(blank=True, null=True, upload_to='id_card')),
                ('dob', models.DateField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='case_media')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=50, null=True)),
                ('height', models.FloatField(blank=True, null=True, validators=[app.validators.validate_severity])),
                ('latittude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('severity', models.FloatField(default=0, validators=[app.validators.validate_severity])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_category_cases', to='app.categorymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='caseimagesmodel',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_case_imgs', to='app.casemodel'),
        ),
        migrations.DeleteModel(
            name='GeneralCaseModel',
        ),
    ]
