# Generated by Django 4.1.1 on 2022-09-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_personmodel_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
