# Generated by Django 4.1.1 on 2022-09-10 12:35

import app.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_casemodel_alter_caseimagesmodel_case_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseCaseModel',
            fields=[
                ('casemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.casemodel')),
                ('who_is_abused', models.CharField(choices=[('MEN', 'MEN'), ('WOMEN', 'WOMEN'), ('CHILD', 'CHILD'), ('OTHER', 'OTHER')], max_length=50)),
                ('abuse_type', models.CharField(choices=[('PHYSICAL', 'PHYSICAL'), ('MENTAL', 'MENTAL')], max_length=50)),
                ('injurured', models.BooleanField(default=False)),
                ('injururies', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('app.casemodel',),
        ),
        migrations.CreateModel(
            name='AggresssionCaseModel',
            fields=[
                ('casemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.casemodel')),
                ('weapon_used', models.BooleanField(default=False)),
                ('weapons_used', models.TextField(blank=True, null=True)),
                ('injurured', models.BooleanField(default=False)),
                ('injururies', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('app.casemodel',),
        ),
        migrations.CreateModel(
            name='ExploitationCaseModel',
            fields=[
                ('casemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.casemodel')),
                ('ragging', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('app.casemodel',),
        ),
        migrations.CreateModel(
            name='IntoxicationCaseModel',
            fields=[
                ('casemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.casemodel')),
                ('drug_or_alcohol_consumed', models.BooleanField(default=False)),
                ('drug_or_alcohol_consumption', models.FloatField(blank=True, null=True, validators=[app.validators.validate_alcoholic])),
                ('troubling_others', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('app.casemodel',),
        ),
        migrations.CreateModel(
            name='MotorIncidentCaseModel',
            fields=[
                ('casemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.casemodel')),
                ('others_property_damaged', models.BooleanField(default=False)),
                ('indirect_or_perposefuly_damaged', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('app.casemodel',),
        ),
        migrations.CreateModel(
            name='OthersCaseModel',
            fields=[
                ('casemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.casemodel')),
                ('information', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('app.casemodel',),
        ),
        migrations.AddField(
            model_name='casemodel',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
