# Generated by Django 4.1.1 on 2022-09-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_personmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=50, null=True),
        ),
    ]
